#!/bin/bash
#
# Copyright (c) 2016 Cisco and/or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# set up the "left" namespace

ip netns add left
ip link add fromleftvpp type veth peer name toleftvpp
ip link set toleftvpp netns left
ip netns exec left ip link set lo up
ip netns exec left ip link set toleftvpp up
ip netns exec left ip addr add 192.168.4.2/24 dev toleftvpp
ip netns exec left route add -net 0.0.0.0/0 gw 192.168.4.1
ip link set fromleftvpp up

